### ISSUE TITLE
when using MGZ's  copy disc function, folder gets named dev_bdvd

### ISSUE THREAD

**Issue by briantho** [Zarh/ManaGunZ#67]
Whenever i copy a game disc from MGZ using the copy function to either the internal ps3 drive or a usb hdd, the output folder name says dev_bdvd. Why does it not name the folder the game or disc name?  For instance, if i copy to a usb drive the output folder looks like this /ntfs0:/PS3ISO/dev_bdvd 

it should say the game name, but this is not the case

**Comment by Zarh** [comment]
On next update the directory will be renamed with the following pattern : "TITLE [TITLE_ID]"
Is it ok for you ?

**Comment by briantho** [comment]
YES. That would be perfect. Thanks. "TITLE [TITLE_ID]" would be much better when copying games. Though i know some people and other programs use "[TITLE_ID] TITLE" Multiman is one of those programs. Is it possible to include a toggle for which output format you would prefer also in the next update? this would be perfect for me. Thanks, and thanks for making such a great program

**Comment by Zarh** [comment]
I though a lot about this, I finally, I decided to not add a toggle because there is too much patterns... sry.
But instead It's going to open the OSK (on screen keyboard) to let the user change the name of the directory himself. By default it will be TITLE [TITLE_ID], because it's the pattern I use.

**Comment by briantho** [comment]
Ok, no problem. Thanks for adding this feature.
