### ISSUE TITLE
PS3 disc bundle with multiple game not correctly submitted the ird?

### ISSUE THREAD

**Issue by gmipf** [Zarh/ManaGunZ#99]
Disc: Rayman Legends + Rayman Origins BLES-02208 http://redump.org/disc/89539/

I have dumped it in Managunz to submit the ird but I think it didn't done it correctly. It seems he just took the Legends part and added it as BLES01896, see db.

**Comment by Zarh** [comment]
It's normal, IRD grab only the main title ID in the param.sfo in the root of game (PS3_GAME/param.sfo) but don't worry the dump will grab every files of your BR.
The ird wasn't uploaded because it already exist in the db, but it increased the 'trust' level, if you search in ps3ird.free.fr BLES01896, you'll find your contribution :)

**Comment by gmipf** [comment]
But shouldn't you add it with the correct serial BLES-02208? How can it increase the trust level of a completely different disc?

**Comment by rhynec** [comment]
@gmipf, MGZ uses more then the TITLE_ID to identity IRDs of different discs, so there shouldn't be any "collision" between these types of hybrid game. Though, I'm curious as to whether the "real title_id" can be found on the DISC.SFB file instead. Would you mind checking (It should be pretty easy to find with a hex editor). 

If the real title_id is in the SFB, perhaps this would be a better way to extract the TITLE_ID @Zarh, and maybe fall back on SFO it it's not? Though, this would probably be a problem for dumps that deleted the file, since they would not be able to be verified, tbh.

**Comment by Zarh** [comment]
I didn't create IRD specification, it was 3k3y team.
The real TitlteID is the one they choose, the other are optionnal and kind of Sub-titleID

**Comment by gmipf** [comment]
[sfb&sfo.zip](https://github.com/Zarh/ManaGunZ/files/7967026/sfb.sfo.zip)

**Comment by Zarh** [comment]
Yes, I have them but I'm sorry I don't need them because the IRD is dumped perfectly look here : [ps3ird.free.fr/?q=BLES01896](http://ps3ird.free.fr/?q=BLES01896)
I can see in the IRD the files of  both games.

**Comment by gmipf** [comment]
OK, good to know. And it seems the db isn't mixing them either right? Someone had that disc dumped it seems then. You can't do anything about the ID and title?
I'm dumping more multigame discs, should I tell you the real ID and title?

**Comment by Zarh** [comment]
Exactly, everything is done to avoid duplicates.
If I change how is grabbed the title it will change the ird signature/hash. So, we will have 2 ird of the same BR.
I didn't create IRD specification files, it was 3k3y team and they created more than 2000 ird.

You don't need to tell me about the real ID and title, ManaGunZ woll do everything :)

Thanks

**Comment by rhynec** [comment]
> Did you received the files?

Sorry, forgot about this issue. The SFB does in fact contain the "real title_id" of the whole disc (BLES-02208). I only wanted to look at the SFB out of curiosity, really. And as Zar said, if he's following the IRD specification, then using the SFO id is safer (while identification can be done through hashing).

**Comment by gmipf** [comment]
But maybe it could be a good idea to add the real id to the db description (not the ird file itself).
